services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    volumes:
      - type: bind
        source: .
        target: /app
      - type: volume
        source: node_module-volume
        target: /app/node_modules
    env_file:
      - .env.local
    ports:
      - 3000:3000

volumes:
  node_module-volume:
    driver: local
